version: "3"

services:
  mysql:
    image: mariadb:10.7
    networks:
      - mattermost
    environment:
      MYSQL_ROOT_HOST: "%"
      MYSQL_ROOT_PASSWORD: mostest
      MYSQL_PASSWORD: mostest
      MYSQL_USER: mmuser
      MYSQL_DATABASE: mattermost_test

  postgres:
    image: postgres:14-alpine
    ports:
      - "5432:5432"
    networks:
      - mattermost
    environment:
      POSTGRES_DB: avadb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres

  mattermost:
    image: "mattermost/mattermost-team-edition:${MATTERMOST_VERSION:-5.39.3}"
    ports:
      - "8065:8065"
    depends_on:
      - mysql
    networks:
      - mattermost
    environment:
      MM_USERNAME: mmuser
      MM_PASSWORD: mostest
      MM_DBNAME: mattermost_test
      MM_SQLSETTINGS_DRIVERNAME: mysql
      MM_SQLSETTINGS_DATASOURCE: "mmuser:mostest@tcp(mysql)/mattermost_test"
      MM_EMAILSETTINGS_SENDEMAILNOTIFICATION: "true"
      MM_EMAILSETTINGS_FEEDBACKEMAIL: "feedback@localhost"
      MM_EMAILSETTINGS_SMTPPORT: "2500"
      MM_EMAILSETTINGS_SMTPSERVER: inbucket
      MM_LOGSETTINGS_ENABLEFILE: "false"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"
      MM_SERVICESETTINGS_ALLOWEDUNTRUSTEDINTERNALCONNECTIONS: "localhost,127.0.0.1,::1"
      MM_SERVICESETTINGS_SITEURL: "http://localhost:8065"

  inbucket:
    image: inbucket/inbucket
    ports:
      - "9000:9000"
      - "2500:2500"
      - "1100:1100"
    networks:
      - mattermost

networks:
  mattermost:
    driver: bridge

